chronontology get batches + tests
dainst/argos pull request #13
Opened 2021-06-06 10:55 UTC by njunghans

2021-06-07 05:32 UTC, dersmon requested changes
Ohne es lokal ausprobiert zu haben, sieht das für mich so aus als würde man aktuell noch nicht alle Daten bekommen.

2021-06-07 05:32 UTC, dersmon commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/chronontology.ex
> -      |> cast(params, [:beginning, :ending])
Wieso ist hier das :ending rausgeflogen?

2021-06-07 05:32 UTC, dersmon commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/chronontology.ex
> +      response =
Es wird nur die erste Seite zurückgegeben, oder? Mit einer Anfrage wird doch vermutlich der gesamte Datenbestand ausgegeben.

2021-06-07 05:32 UTC, dersmon commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/chronontology.ex
> +    def get_by_date(%Date{} = date) do
s.o.

2021-06-07 08:53 UTC, njunghans commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/chronontology.ex
> -      |> cast(params, [:beginning, :ending])
es gibt ja auch Perioden die noch nicht beendet sind oder ? Zumindest gibt es daten ohne ending

2021-06-14 06:40 UTC, dersmon commented
Wolltest du den Harvester noch hier hinzufügen?

2021-06-14 12:44 UTC, dersmon commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/chronontology.ex
> +               %{optional(<<_::48, _::_*8>>) => binary | %{optional(<<_::24, _::_*8>>) => any}}}
Da haste aus versehen reingeklickt, wa?

2021-06-14 12:52 UTC, dersmon commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/chronontology.ex
> +
Was ist "string: string" für eine Syntax? Hast du ausprobiert ob der da überhaupt reingeht?

2021-06-14 12:54 UTC, dersmon reviewed
Die parse_any_to_numeric verstehe ich gerade nicht so ganz.

2021-06-15 06:25 UTC, dersmon approved these changes

2021-06-15 13:49 UTC, merged