parse urls
dainst/argos pull request #21
Opened 2021-08-10 11:31 UTC by njunghans

#SD-1412

2021-08-10 12:25 UTC, dersmon requested changes
Add teh tests! :test_tube:  :grin:

2021-08-10 12:25 UTC, dersmon commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/bibliography.ex
> +        end)
Das brauchste eigentlich nicht async zu machen. Es werden von parse_url ja keine HTTP Anfragen o.ä. generiert. Die  Zeilen sollte man durch ein einfaches  `Enum.map(&parse_url/1)` ersetzen können.

2021-08-10 12:25 UTC, dersmon commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/bibliography.ex
> +    end
Das müsste man eigentlich weglassen können. Wenn du oben `Enum.map` aufrufst, wird das auf jedes Element der Liste angewendet. Das heißt hier sollten nur einzelne url-Einträge ankommen.

2021-08-10 12:25 UTC, dersmon commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/bibliography.ex
> +          "text" => url["desc"]
Bin mir gerade nicht sicher, ob "desc" in 100% der Fälle gesetzt ist oder auch mal leer sein könnte. Vielleicht wäre für nicht vorhanden/leer ganz gut einen Fallback-Wert zu haben.

2021-08-10 12:25 UTC, dersmon commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/bibliography.ex
> +    defp parse_url(url) do
Du könntest dir die Werte auch direkt mit einem pattern match rausholen:
```elixir
defp parse_url(%{"url" => url, "desc" => desc}) do
```
Das würde die restliche Funktion vielleicht etwas vereinfachen.

2021-08-10 12:27 UTC, njunghans commented on apps/argos_aggregation/lib/argos_aggregation/data_sources/bibliography.ex
> +        end)
macht sinn!

2021-08-11 07:17 UTC, dersmon approved these changes

2021-08-11 07:23 UTC, dersmon commented
Habe das doch nochmal in einen eigenen Test umgewandelt.

2021-08-11 08:13 UTC, merged